--COMP214-009 Assignment 4 - Group Project
--Winmonopolet Database
--Group 5
 
--INDEXES

-- DROP INDEXES SECTION
DROP INDEX BRAND_NAME_IDX;
DROP INDEX PRODUCT_NAME_IDX;
DROP INDEX FIRST_NAME_IDX;
DROP INDEX EMAIL_IDX;
DROP INDEX customer_province_idx;

--1 INDEX FOR BRAND NAME IN WINMONO_BRAND TABLE
CREATE INDEX BRAND_NAME_IDX
  ON WINMONO_BRAND (BRAND_NAME);

--TEST INDEX
SELECT TABLE_NAME, INDEX_NAME, INDEX_TYPE
FROM USER_INDEXES
WHERE TABLE_NAME='WINMONO_BRAND';

--2 INDEX FOR PRODUCT NAME IN WINMONO_PRODCUTS TABLE
CREATE INDEX PRODUCT_NAME_IDX
ON WINMONO_PRODUCTS (PRODUCT_NAME);

--TEST INDEX
SELECT TABLE_NAME, INDEX_NAME, INDEX_TYPE
FROM USER_INDEXES
WHERE TABLE_NAME='WINMONO_PRODUCTS';

--3 INDEX FOR FIRST NAME IN WINMONO_CUSTOMER TABLE
CREATE INDEX FIRST_NAME_IDX
ON WINMONO_CUSTOMER (FIRST_NAME);

--4 BITMAP INDEX ON CUSTOMERS TABLE
CREATE BITMAP INDEX CUSTOMER_PROVINCE_IDX
ON WINMONO_CUSTOMER(PROVINCE);

--TEST INDEX
SELECT TABLE_NAME, INDEX_NAME, INDEX_TYPE
FROM USER_INDEXES
WHERE TABLE_NAME='WINMONO_CUSTOMER';


EXPLAIN PLAN FOR 
SELECT 
    *
FROM
    winmono_customer
WHERE
    province = 'ON';
   
SELECT 
    PLAN_TABLE_OUTPUT 
FROM 
    TABLE(DBMS_XPLAN.DISPLAY());      


--5 INDEX EMAIL IN WINMONO_BASKET TABLE
CREATE INDEX EMAIL_IDX
ON WINMONO_BASKET (EMAIL);

--TEST INDEX
SELECT TABLE_NAME, INDEX_NAME, INDEX_TYPE
FROM USER_INDEXES
WHERE TABLE_NAME='WINMONO_BASKET';



